# GET http://localhost:3001/backend/


POST http://localhost:3001/api/redirect/
Content-Type: application/json

{
     "url": "https://docs.datomic.com/datomic-overview.html",
     "slug": "datomiz"
}


# Content-Type: application/json
# Authorization: Bearer YOUR_TOKEN

# POST https://api.example.com/users
