GET http://localhost:3001/julieta/

# POST http://localhost:3001/api/redirect/
# Content-Type: application/json

# {
#      "url": "hitoiki.co"
# }

# POST http://localhost:3001/api/redirect/
# Content-Type: application/json

# {
#      "url": "https://www.hitoiki.co",
#      "slug": ""
# }


# POST https://hitoiki.co/api/redirect/
# Content-Type: application/json

# {
#      "url": "https://www.hitoiki.co"
# }
