GET http://localhost:3001/


# POST http://localhost:3001/api/redirect/
# Content-Type: application/json

# {
#     "url": "https://www.youtube.com/watch?v=0mrguRPgCzI&t=1936s"
# }


# Content-Type: application/json
# Authorization: Bearer YOUR_TOKEN

# POST https://api.example.com/users
