(ns shorturl.db
  (:require [next.jdbc :as jdbc]
            [honey.sql :as sql]
            [honey.sql.helpers :as h]
            [shorturl.env :refer [env]]))

(def db-spec
  "Database connection specification for PostgreSQL.
   Uses environment variables from env namespace for configuration,
   secrets from actual environment."
  {:dbtype "postgresql"
   :dbname (env :DBNAME)
   :host (env :HOST)
   :user (env :SHORTURL_DB_USER)
   :password (env :SHORTURL_DB_PASSWORD)
   :ssl (env :SSL)
   :sslmode (env :SSLMODE)})

(def ds
  "JDBC datasource created from database specification."
  (jdbc/get-datasource db-spec))

(defn execute-query
  "Execute an SQL query against the database.
   Takes a query vector or map (typically generated by honey.sql)."
  [q]
  (jdbc/execute! ds q))

;; ============================================================================
;; URL Shortening Functions
;; ============================================================================

(defn get-url
  "Retrieve the original URL for a given short code/slug.
   Returns nil if the slug doesn't exist."
  [slug]
  (-> (execute-query (-> (h/select :*)
                         (h/from :shortened_urls)
                         (h/where [:= :slug slug])
                         (sql/format)))
      first
      :shortened_urls/original_url))

(defn insert-url-redirection!
  "Create a new URL redirection by storing the original URL and its short code.

   Parameters:
   - url: The original URL to be shortened
   - slug: The unique short code/identifier
   - user-id: (optional) The ID of the user creating this URL

   Returns:
   - The result of the insert operation"
  ([url slug]
   (insert-url-redirection! url slug nil))

  ([url slug user-id]
   (execute-query (-> (h/insert-into :shortened_urls)
                      (h/columns :original_url :slug :user_id)
                      (h/values [[url slug user-id]])
                      (sql/format)))))

;; ============================================================================
;; User Management Functions
;; ============================================================================

(defn get-user-by-firebase-uid
  "Retrieve a user by their Firebase UID.
   Returns the entire user record or nil if not found.

   Parameters:
   - firebase-uid: The unique identifier from Firebase Authentication

   Returns:
   - The user record as a map, or nil if no user is found"
  [firebase-uid]
  (-> (execute-query (-> (h/select :*)
                         (h/from :users)
                         (h/where [:= :firebase_uid firebase-uid])
                         (sql/format)))
      first))

(defn create-user!
  "Create a new user record from Firebase authentication data.

   Parameters:
   - firebase-uid: The unique identifier from Firebase Authentication
   - email: The user's email address
   - display-name: The user's display name (optional)

   Returns:
   - The result of the insert operation"
  [firebase-uid email display-name]
  (execute-query (-> (h/insert-into :users)
                     (h/columns :firebase_uid :email :display_name :last_login)
                     (h/values [[firebase-uid email display-name
                                 (java.sql.Timestamp. (System/currentTimeMillis))]])
                     (sql/format))))

(defn update-user-last-login!
  "Update the last_login timestamp for a user.

   Parameters:
   - firebase-uid: The unique identifier from Firebase Authentication

   Returns:
   - The result of the update operation"
  [firebase-uid]
  (execute-query (-> (h/update :users)
                     (h/set {:last_login (java.sql.Timestamp. (System/currentTimeMillis))})
                     (h/where [:= :firebase_uid firebase-uid])
                     (sql/format))))

(defn get-user-id-by-firebase-uid
  "Get the internal user ID from a Firebase UID.

   Parameters:
   - firebase-uid: The Firebase Authentication UID

   Returns:
   - The user's internal database ID, or nil if not found"
  [firebase-uid]
  (-> (execute-query (-> (h/select :id)
                         (h/from :users)
                         (h/where [:= :firebase_uid firebase-uid])
                         (sql/format)))
      first
      :users/id))

(defn get-user-slugs
  "Get all shortened URLs created by a user.

   Parameters:
   - user-id: The internal user database ID

   Returns:
   - A list of maps containing :slug, :original_url, and :created_at
     Ordered by creation date (newest first)"
  [user-id]
  (execute-query (-> (h/select :slug :original_url :created_at)
                     (h/from :shortened_urls)
                     (h/where [:= :user_id user-id])
                     (h/order-by [:created_at :desc])
                     (sql/format))))

(defn slug-belongs-to-user?
  "Check if a slug belongs to a specific user.

   Parameters:
   - slug: The short URL slug
   - user-id: The internal user database ID

   Returns:
   - true if the slug exists and belongs to the user, false otherwise"
  [slug user-id]
  (-> (execute-query (-> (h/select :id)
                         (h/from :shortened_urls)
                         (h/where [:and
                                   [:= :slug slug]
                                   [:= :user_id user-id]])
                         (sql/format)))
      first
      boolean))

(defn delete-slug!
  "Delete a shortened URL by its slug.

   Parameters:
   - slug: The short URL slug to delete

   Returns:
   - The result of the delete operation"
  [slug]
  (execute-query (-> (h/delete-from :shortened_urls)
                     (h/where [:= :slug slug])
                     (sql/format))))

(comment
  ;; ============================================================================
  ;; Development & Testing
  ;; ============================================================================

  ;; Test database connection
  (jdbc/execute! ds ["SELECT 1"])

  ;; View all users
  (execute-query (sql/format {:select [:*] :from [:users]}))

  ;; View all shortened URLs
  (execute-query (sql/format {:select [:*] :from [:shortened_urls]}))

  ;; Test URL creation (anonymous)
  (insert-url-redirection! "https://clojure.org" "clojure")

  ;; Test URL creation (with user)
  (insert-url-redirection! "https://github.com/clojure" "clj-gh" 1)

  ;; Test URL retrieval
  (get-url "clojure")

  ;; Test user creation
  (create-user! "test-firebase-uid" "test@example.com" "Test User")

  ;; Test user lookup
  (get-user-by-firebase-uid "test-firebase-uid")

  ;; Test login update
  (update-user-last-login! "test-firebase-uid")

  ;; Test getting user ID
  (get-user-id-by-firebase-uid "test-firebase-uid")

  ;; Test getting user's slugs (assuming user_id = 1)
  (get-user-slugs 1)

  ;; Test ownership check
  (slug-belongs-to-user? "clojure" 1)

  ;; Test deleting a slug
  (delete-slug! "test-slug")

  ;; Clean slate - delete all URLs
  (execute-query (sql/format {:delete-from :shortened_urls}))

  ;; View schema information
  (execute-query
   (sql/format
    {:select [:table_name :column_name :data_type :is_nullable]
     :from [:information_schema.columns]
     :where [:and
             [:in :table_name ["users" "shortened_urls"]]
             [:= :table_schema "public"]]
     :order-by [:table_name :ordinal_position]})))
